version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          cypress-command: 'npx cypress run --spec cypress/e2e/stagingBetaVendor/calendar/bv-stg-newchck.cy.js'