/// <reference types="cypress" />
/// <reference types="cypress-xpath" />

const { should } = require("chai")

const login = (name, username, password) => {
  cy.session(name, () => {
    cy.visit('https://beta.vendor.bookr-dev.com/')
    cy.url().should('include', 'https://beta.vendor.bookr-dev.com/auth')
    cy.get('[type="text"]').should('be.visible')
    cy.get('[type="password"]').should('be.visible')
    cy.xpath('//button[text()="Login"]').should('be.visible')
    cy.get('[type="text"]').type(username, { force: true, delay: 50 })
    cy.get('[type="password"]').type(password, { force: true, delay: 50 })
    cy.intercept('POST', '/api/main/auth/login').as('sign')
    cy.xpath('//button[text()="Login"]').click()
    cy.wait('@sign').then((interception) => {
      expect(interception.response.statusCode).to.equal(200)
    })
  })
}

describe.only('Beta Vendor Admin | Inventory | Create products| logged with Admin credentials', () => {

  beforeEach(() => {
    login('Admin Section', 'testsalon', 'testsalon1o')
  })

  afterEach(() => {
    // cy.visit('https://beta.vendor.bookr-dev.com/auth?nativeLogout=true')
    cy.clearCookies()
  })

  it('Verify it is possible access to the Inventory/Product section- Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
  })

  it('Verify the it is possible access to the Create product form - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.wait(100)
  })

//Navigation within the Creation Tabs
  it('Verify the it is possible access to the Create product/Basic info tab form - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.contains('h6', 'Basic Info').should('exist')
    cy.contains('span', 'Product Name').should('exist')
    cy.contains('span', 'Product Bar Code').should('exist')
    cy.contains('span', 'Product Measurement').should('exist')
    cy.contains('span', 'Product Category').should('exist')
    cy.contains('span', 'Product Brand').should('exist')
    cy.contains('span', 'Short Description').should('exist')
    cy.contains('span', 'Product Description').should('exist')
    cy.wait(100)
  })

  it('Verify the it is possible access to the Create product/Pricing tab form - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Pricing').should('exist')
    cy.contains('button', 'Pricing').click({ force: true })
    cy.contains('h6', 'Pricing').should('exist')
    cy.contains('span', 'Supply Price').should('exist')
    cy.contains('span', 'Retail Price').should('exist')
    cy.contains('span', 'Enable Retail Sales').should('exist')
    cy.contains('span', 'Tax').should('exist')
    cy.wait(100)
  })

  it('Verify the it is possible access to the Create product/Inventory tab form - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6','Products').should('exist')
    cy.contains('button','Add New').should('exist')
    cy.contains('button','Add New').click({ force: true })
    cy.contains('h3','Create Product').should('exist')
    cy.contains('div>button','Inventory').should('exist')
    cy.contains('div>button','Inventory').click({ force: true })
    cy.contains('div>h6','Inventory').should('exist')
    // cy.contains('label/span','`SKU (Stock Keeping Unit)`').should('exist')
    cy.contains('span','Supplier').should('exist')
    // cy.contains('label/span','Current Stock Qantity').should('exist')
    // cy.contains('span','Low Stock Level').should('exist')
    cy.wait(100)
  })

// Create Non successfully
  it('Verify Product Name is the required field by trying to create a product leaving empty all the fields- Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.wait(100)
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product name is required').should('exist')
    cy.wait(100)
  })

  it('Verify Product Name is the only required field by tring to create a product, filling up barcode only - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder="Enter product barcode e.g 123456789"]').should('exist')
    cy.get('input[placeholder="Enter product barcode e.g 123456789"]').type('1234567890')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product name is required').should('exist')
    cy.wait(100)
  })

  it('Verify Product Name is the only required field by trying to create a product, filling up Product Measurement without unit only - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder="Enter product measurement"]').should('exist')
    cy.get('input[placeholder="Enter product measurement"]').type('1234567890')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product name is required').should('exist')
    cy.wait(100)
  })

  it('Verify Product Name is the only required field by trying to create a product filling up Product Measurement with unit only - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder="Enter product measurement"]').should('exist')
    cy.get('input[placeholder="Enter product measurement"]').type('1234567890')
    cy.contains('option', 'Select Unit').should('exist')
    cy.get('select').select('l')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product name is required').should('exist')
    cy.wait(100)
  })

  it('Verify Product Name is the only required field by trying to create a product filling up Short Description only - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder="Enter short description of the product"]').should('exist')
    cy.get('input[placeholder="Enter short description of the product"]').type('1234567890')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product name is required').should('exist')
    cy.wait(100)
  })

  it('Verify Product Name is the only required field by trying to create a product filling up Product Description only - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('textarea[placeholder="Enter product description"]').should('exist')
    cy.get('textarea[placeholder="Enter product description"]').type('1234567890')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product name is required').should('exist')
    cy.wait(100)
  })

  it('Verify Product Name is the only required field by triying to create a product filling up Supply Price only - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Pricing').should('exist')
    cy.contains('button', 'Pricing').click({ force: true })
    cy.contains('h6', 'Pricing').should('exist')
    cy.contains('span', 'Supply Price').should('exist')
    cy.contains('span', 'Retail Price').should('exist')
    cy.contains('span', 'Enable Retail Sales').should('exist')
    cy.contains('span', 'Tax').should('exist')
    cy.contains('label>span', 'Supply Price').parents('label').next('div').find('input').type('1234567890')
    cy.wait(100)
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product name is required').should('exist')
    cy.wait(100)
  })

  it('Verify Product Name is the only required field by trying to create a product by filling up Retail Price only - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Pricing').should('exist')
    cy.contains('button', 'Pricing').click({ force: true })
    cy.contains('h6', 'Pricing').should('exist')
    cy.contains('span', 'Supply Price').should('exist')
    cy.contains('span', 'Retail Price').should('exist')
    cy.contains('span', 'Enable Retail Sales').should('exist')
    cy.contains('span', 'Tax').should('exist')
    cy.contains('label>span', 'Supply Price').should('exist')
    cy.contains('label>span', 'Retail Price').parents('label').next('div').find('input').type('1234567890')
    cy.wait(100)
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product name is required').should('exist')
    cy.wait(100)
  })

  it('Verify Product Measuarement cannot be submited without Units - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product filled up with Product Name and Barcode')
    cy.get('input[placeholder="Enter product measurement"]').should('exist')
    cy.get('input[placeholder="Enter product measurement"]').type('123')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'measure.unit must be one of the following values: ml, l, g, kg, oz, lb, cm, ft, in, whole').should('exist')
    cy.wait(100)
  })

//Create succesfully
  it('Verify it is possible to create a Product by filling up only the Product Name - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product filled up with Product Name only')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product created successfully').should('exist')
    cy.wait(100)
  })

  it('Verify Product is create successfully by filling up Price Name and Product Bar Code - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product filled up with Product Name and Barcode')
    cy.get('input[placeholder="Enter product barcode e.g 123456789"]').should('exist')
    cy.get('input[placeholder="Enter product barcode e.g 123456789"]').type('asdfgh4523')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product created successfully').should('exist')
    cy.wait(100)
  })

  it('Verify Product is create successfully by filling up Price Name and Selecting a Product Category - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product filled up with Price Name and Category')
    cy.contains('label>span', 'Product Category').should('exist')
    cy.contains('label>span', 'Product Category').parents('label').next('div').find('input').click({ force: true })
    cy.contains('h3', 'Categories').should('exist')
    cy.get('section>div>ul>*').first().click({ force: true })
    cy.wait(1000)
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product created successfully').should('exist')
    cy.wait(100)
  })

  it('Verify Product is create successfully by filling up Price Name and Selecting a Product Brand - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product filled up with Price Name and Brand')
    cy.contains('label>span', 'Product Brand').should('exist')
    cy.contains('label>span', 'Product Brand').parents('label').next('div').find('input').click({ force: true })
    cy.contains('h3', 'Brands').should('exist')
    cy.get('section>div>ul>*').first().click({ force: true })
    cy.wait(1000)
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product created successfully').should('exist')
    cy.wait(100)
  })

  it('Verify Product is create successfully by filling up Price Name and Product description - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product filled up with Product Name and Short Description')
    cy.get('input[placeholder="Enter short description of the product"]').should('exist')
    cy.get('input[placeholder="Enter short description of the product"]').type('This is a short description of the product')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product created successfully').should('exist')
    cy.wait(100)
  })

  it('Verify Product is create successfully by filling up Price Name and Product description - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product filled up with Product Name and Product Description')
    cy.get('input[placeholder="Enter product description"]').should('exist')
    cy.get('input[placeholder="Enter product description"]').type('This is a product description of the product')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product created successfully').should('exist')
    cy.wait(100)
  })

  it('Verify Product is create successfully by filling up Price Name and Supply Price - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Pricing').should('exist')
    cy.contains('button', 'Pricing').click({ force: true })
    cy.contains('h6', 'Pricing').should('exist')
    cy.contains('span', 'Supply Price').should('exist')
    cy.contains('span', 'Retail Price').should('exist')
    cy.contains('span', 'Enable Retail Sales').should('exist')
    cy.contains('span', 'Tax').should('exist')
    cy.contains('label>span', 'Supply Price').should('exist')
    cy.contains('label>span', 'Supply Price').parents('label').next('div').find('input').type('12345')
    cy.wait(100)
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product filled up with Price name and Supply Price')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product created successfully').should('exist')
  })

  it('Verify Product is create successfully by filling up Price Name and Retail Price - Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.contains('button', 'Add New').should('exist')
    cy.contains('button', 'Add New').click({ force: true })
    cy.contains('h3', 'Create Product').should('exist')
    cy.contains('button', 'Pricing').should('exist')
    cy.contains('button', 'Pricing').click({ force: true })
    cy.contains('h6', 'Pricing').should('exist')
    cy.contains('span', 'Supply Price').should('exist')
    cy.contains('span', 'Retail Price').should('exist')
    cy.contains('span', 'Enable Retail Sales').should('exist')
    cy.contains('span', 'Tax').should('exist')
    cy.contains('span', 'Retail Price').should('exist')
    cy.contains('label>span', 'Retail Price').parents('label').next('div').find('input').type('67890')
    cy.wait(100)
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder = "Enter product name"]').should('exist')
    cy.get('input[placeholder = "Enter product name"]').type('Product with Retail Price')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
    cy.contains('span', 'Product created successfully').should('exist')
  })

//Edit Successfully
  it('Verify the option to edit production is available from the Inventory/Product list section- Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('tbody>*').should('exist')
    cy.get('tbody>*').first().click({ force: true })
    cy.contains('h3', 'Product Details').should('exist')
    cy.contains('button', 'Edit').should('exist')
    cy.contains('button', 'Edit').click({ force: true })
    cy.contains('h3', 'Edit Product Details').should('exist')
  })

  it('Verify it is not possible edit product messure without adding a unit from the Inventory/Product list section- Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('tbody>*').should('exist')
    cy.get('tbody>*').first().click({ force: true })
    cy.contains('h3', 'Product Details').should('exist')
    cy.contains('button', 'Edit').should('exist')
    cy.contains('button', 'Edit').click({ force: true })
    cy.contains('h3', 'Edit Product Details').should('exist')
    cy.contains('button', 'Basic Info').should('exist')
    cy.contains('button', 'Basic Info').click({ force: true })
    cy.get('input[placeholder="Enter product measurement"]').should('exist')
    cy.get('input[placeholder="Enter product measurement"]').type('1234567890')
    cy.contains('button', 'Save').should('exist')
    cy.contains('button', 'Save').click({ force: true })
  })

//Delete Successfully
  it('Verify it is possible delete products from the Inventory/Product list section- Admin credentials', () => {
    cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('tbody>*').should('exist')
    cy.get('tbody>*').first().click({ force: true })
    cy.contains('h3', 'Product Details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
    cy.get('tbody').find('tr').its('length').then(count => {
      if (count) {   // not count >= 0, because 0 means no elements
        cy.log(`there are ${count - 1} elements`)
      }
    })
  })

  // it.only('Verify it is possible delete products from the Inventory/Product list section- Admin credentials', () => {
  //   cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
  //   cy.contains('Inventory').should('exist')
  //   cy.contains('Inventory').click({ force: true })
  //   cy.contains('Products').should('exist')
  //   cy.contains('Products').click({ force: true })
  //   cy.contains('h6', 'Products').should('exist')
  //   cy.get('tbody>*').should('exist')
  //   cy.get('tbody>*').first().click({ force: true })
  //   cy.contains('h3', 'Product Details').should('exist')
  //   cy.contains('button', 'Delete').should('exist')
  //   cy.contains('button', 'Delete').click({ force: true })
  //   cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
  //   cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
  //   cy.contains('span', 'Product deleted successfully').should('exist')
  //   cy.get('tbody').find('tr').its('length').then(count => {
  //     if (count) {   // not count >= 0, because 0 means no elements
  //       cy.log(`there are ${count - 1} elements`)
  //     }
  //   })
  // })


  // it.only('Verify it is possible delete products from the Inventory/Product list section- Admin credentials', () => {
  //   cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
  //   cy.contains('Inventory').should('exist')
  //   cy.contains('Inventory').click({ force: true })
  //   cy.contains('Products').should('exist')
  //   cy.contains('Products').click({ force: true })
  //   cy.contains('h6', 'Products').should('exist')
  //   cy.get('tbody>*').should('exist')
  //   cy.get('tbody>*').first().click({ force: true })
  //   cy.contains('h3', 'Product Details').should('exist')
  //   cy.contains('button', 'Delete').should('exist')
  //   cy.contains('button', 'Delete').click({ force: true })
  //   cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
  //   cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
  //   cy.contains('span', 'Product deleted successfully').should('exist')
  //   cy.get('tbody').find('tr').its('length').then(count => {
  //     if (count) {   // not count >= 0, because 0 means no elements
  //       cy.log(`there are ${count - 1} elements`)
  //     }
  //   })
  // })

  // it.only('Verify it is possible delete products from the Inventory/Product list section- Admin credentials', () => {
  //   cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
  //   cy.contains('Inventory').should('exist')
  //   cy.contains('Inventory').click({ force: true })
  //   cy.contains('Products').should('exist')
  //   cy.contains('Products').click({ force: true })
  //   cy.contains('h6', 'Products').should('exist')
  //   cy.get('tbody>*').should('exist')
  //   cy.get('tbody>*').first().click({ force: true })
  //   cy.contains('h3', 'Product Details').should('exist')
  //   cy.contains('button', 'Delete').should('exist')
  //   cy.contains('button', 'Delete').click({ force: true })
  //   cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
  //   cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
  //   cy.contains('span', 'Product deleted successfully').should('exist')
  //   cy.get('tbody').find('tr').its('length').then(count => {
  //     if (count) {   // not count >= 0, because 0 means no elements
  //       cy.log(`there are ${count - 1} elements`)
  //     }
  //   })
  // })

  // it.only('Verify it is possible delete products from the Inventory/Product list section- Admin credentials', () => {
  //   cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
  //   cy.contains('Inventory').should('exist')
  //   cy.contains('Inventory').click({ force: true })
  //   cy.contains('Products').should('exist')
  //   cy.contains('Products').click({ force: true })
  //   cy.contains('h6', 'Products').should('exist')
  //   cy.get('tbody>*').should('exist')
  //   cy.get('tbody>*').first().click({ force: true })
  //   cy.contains('h3', 'Product Details').should('exist')
  //   cy.contains('button', 'Delete').should('exist')
  //   cy.contains('button', 'Delete').click({ force: true })
  //   cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
  //   cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
  //   cy.contains('span', 'Product deleted successfully').should('exist')
  //   cy.get('tbody').find('tr').its('length').then(count => {
  //     if (count) {   // not count >= 0, because 0 means no elements
  //       cy.log(`there are ${count - 1} elements`)
  //     }
  //   })
  // })

  // it('Verify it is possible delete products from the Inventory/Product list section- Admin credentials', () => {
  //   cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
  //   cy.contains('Inventory').should('exist')
  //   cy.contains('Inventory').click({ force: true })
  //   cy.contains('Products').should('exist')
  //   cy.contains('Products').click({ force: true })
  //   cy.contains('h6', 'Products').should('exist')
  //   cy.get('tbody>*').should('exist')
  //   cy.get('tbody>*').first().click({ force: true })
  //   cy.contains('h3', 'Product Details').should('exist')
  //   cy.contains('button', 'Delete').should('exist')
  //   cy.contains('button', 'Delete').click({ force: true })
  //   cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
  //   cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
  //   cy.contains('span', 'Product deleted successfully').should('exist')
  //   cy.get('tbody').find('tr').its('length').then(count => {
  //     if (count) {   // not count >= 0, because 0 means no elements
  //       cy.log(`there are ${count - 1} elements`)
  //     }
  //   })
  // })

  // it('Verify it is possible delete products from the Inventory/Product list section- Admin credentials', () => {
  //   cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
  //   cy.contains('Inventory').should('exist')
  //   cy.contains('Inventory').click({ force: true })
  //   cy.contains('Products').should('exist')
  //   cy.contains('Products').click({ force: true })
  //   cy.contains('h6', 'Products').should('exist')
  //   cy.get('tbody>*').should('exist')
  //   cy.get('tbody>*').each(()=> {
  //     cy.get('tbody>*').first().click()
  //     cy.contains('h3', 'Product Details').should('exist')
  //     cy.contains('button', 'Delete').should('exist')
  //     cy.contains('button', 'Delete').click({ force: true })
  //     cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
  //     cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
  //     cy.contains('span', 'Product deleted successfully').should('exist')
  //   })
  // })

  // it('Verify it is possible delete products from the Inventory/Product list section- Admin credentials', () => {
  //   cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
  //   cy.contains('Inventory').should('exist')
  //   cy.contains('Inventory').click({ force: true })
  //   cy.contains('Products').should('exist')
  //   cy.contains('Products').click({ force: true })
  //   cy.contains('h6', 'Products').should('exist')
  //   cy.get('tbody>*').should('exist')
  //   cy.get('tbody>*').each(($row)=> {
  //     cy.wrap($row).click()
  //     cy.contains('h3', 'Product Details').should('exist')
  //     cy.contains('button', 'Delete').should('exist')
  //     cy.contains('button', 'Delete').click({ force: true })
  //     cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
  //     cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
  //     cy.contains('span', 'Product deleted successfully').should('exist')
  //   })
  // })
})
