/// <reference types="cypress" />
/// <reference types="cypress-xpath" />

const { should } = require("chai")

const login = (name, username, password) => {
  cy.session(name, () => {
    //cy.visit('https://beta.vendor.bookr-dev.com/')
    cy.visit(Cypress.env("URL_BetaVendor_Staging"))
    cy.url().should('include', 'https://beta.vendor.bookr-dev.com/auth')
    cy.get('[type="text"]').should('be.visible')
    cy.get('[type="password"]').should('be.visible')
    cy.xpath('//button[text()="Login"]').should('be.visible')
    cy.get('[type="text"]').type(username, { force: true, delay: 50 })
    cy.get('[type="password"]').type(password, { force: true, delay: 50 })
    cy.intercept('POST', '/api/main/auth/login').as('sign')
    cy.xpath('//button[text()="Login"]').click()
    cy.wait('@sign').then((interception) => {
      expect(interception.response.statusCode).to.equal(200)
    })
  })
}

const accessBrand = () => {
  //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
  cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
  cy.contains('Inventory').should('exist')
  cy.contains('Inventory').click({ force: true })
  cy.contains('Options').should('exist')
  cy.contains('Options').click({ force: true })
  cy.contains('Brand').should('exist')
  cy.contains('Brand').click({ force: true })
}

describe('Beta Vendor Admin | Inventory | Delete Brands| logged with Admin credentials', () =>{

    beforeEach(() => {
      cy.login('Admin Section', Cypress.env("Vendor_Admin_Username_Staging"), Cypress.env("Vendor_Admin_Password_Staging"))
    })

    afterEach(() => {
        cy.clearCookies()
    })

    it.only('Verify it is possible delete brand', () => {
        cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
        cy.contains('Inventory').click({ force: true })
        cy.contains('Products').click({ force: true })
        cy.contains('Options').click({ force: true })
        cy.contains('li','Brand').click({ force: true })
        cy.get('section>div>ul>li>*').eq(0).click()
        cy.contains('button','Delete').click({ force: true })
        cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
    })

    it('Verify it is possible delete brand', () => {
      cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
      cy.contains('Inventory').should('exist')
      cy.contains('Inventory').click({ force: true })
      cy.contains('Products').should('exist')
      cy.contains('Products').click({ force: true })
      cy.contains('Options').should('exist')
      cy.contains('Options').click({ force: true })
      cy.contains('li','Brand').should('exist')
      cy.contains('li','Brand').click({ force: true })
      cy.get('section>div>ul>li>*').eq(1).click()
      cy.contains('button','Delete').click({ force: true })
      cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
  })

  it('Verify it is possible delete brand', () => {
    cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('Options').should('exist')
    cy.contains('Options').click({ force: true })
    cy.contains('li','Brand').should('exist')
    cy.contains('li','Brand').click({ force: true })
    cy.get('section>div>ul>li>*').eq(3).click()
    cy.contains('button','Delete').click({ force: true })
    cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist') 
})

it('Verify it is possible delete brand', () => {
  cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
  cy.contains('Inventory').should('exist')
  cy.contains('Inventory').click({ force: true })
  cy.contains('Products').should('exist')
  cy.contains('Products').click({ force: true })
  cy.contains('Options').should('exist')
  cy.contains('Options').click({ force: true })
  cy.contains('li','Brand').should('exist')
  cy.contains('li','Brand').click({ force: true })
  cy.get('section>div>ul>li>*').eq(3).click()
  cy.contains('button','Delete').click({ force: true })
  cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
})

it('Verify it is possible delete brand', () => {
  cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
  cy.contains('Inventory').should('exist')
  cy.contains('Inventory').click({ force: true })
  cy.contains('Products').should('exist')
  cy.contains('Products').click({ force: true })
  cy.contains('Options').should('exist')
  cy.contains('Options').click({ force: true })
  cy.contains('li','Brand').should('exist')
  cy.contains('li','Brand').click({ force: true })
  cy.get('section>div>ul>li>*').eq(3).click()
  cy.contains('button','Delete').click({ force: true })
  cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
})

it('Verify it is possible delete brand', () => {
  cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
  cy.contains('Inventory').should('exist')
  cy.contains('Inventory').click({ force: true })
  cy.contains('Products').should('exist')
  cy.contains('Products').click({ force: true })
  cy.contains('Options').should('exist')
  cy.contains('Options').click({ force: true })
  cy.contains('li','Brand').should('exist')
  cy.contains('li','Brand').click({ force: true })
  cy.get('section>div>ul>li>*').eq(3).click()
  cy.contains('button','Delete').click({ force: true })
  cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
})

it('Verify it is possible delete brand', () => {
cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
cy.contains('Inventory').should('exist')
cy.contains('Inventory').click({ force: true })
cy.contains('Products').should('exist')
cy.contains('Products').click({ force: true })
cy.contains('Options').should('exist')
cy.contains('Options').click({ force: true })
cy.contains('li','Brand').should('exist')
cy.contains('li','Brand').click({ force: true })
cy.get('section>div>ul>li>*').eq(3).click()
cy.contains('button','Delete').click({ force: true })
cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
})

it('Verify it is possible delete brand', () => {
cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
cy.contains('Inventory').should('exist')
cy.contains('Inventory').click({ force: true })
cy.contains('Products').should('exist')
cy.contains('Products').click({ force: true })
cy.contains('Options').should('exist')
cy.contains('Options').click({ force: true })
cy.contains('li','Brand').should('exist')
cy.contains('li','Brand').click({ force: true })
cy.get('section>div>ul>li>*').eq(3).click()
cy.contains('button','Delete').click({ force: true })
cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
})

it('Verify it is possible delete brand', () => {
cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
cy.contains('Inventory').should('exist')
cy.contains('Inventory').click({ force: true })
cy.contains('Products').should('exist')
cy.contains('Products').click({ force: true })
cy.contains('Options').should('exist')
cy.contains('Options').click({ force: true })
cy.contains('li','Brand').should('exist')
cy.contains('li','Brand').click({ force: true })
cy.get('section>div>ul>li>*').eq(3).click()
cy.contains('button','Delete').click({ force: true })
cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
})

it('Verify it is possible delete brand', () => {
cy.visit(Cypress.env("URL_BetaVendor_Staging") + 'auth')
cy.contains('Inventory').should('exist')
cy.contains('Inventory').click({ force: true })
cy.contains('Products').should('exist')
cy.contains('Products').click({ force: true })
cy.contains('Options').should('exist')
cy.contains('Options').click({ force: true })
cy.contains('li','Brand').should('exist')
cy.contains('li','Brand').click({ force: true })
cy.get('section>div>ul>li>*').eq(3).click()
cy.contains('button','Delete').click({ force: true })
cy.contains('span', 'Brand deleted', { matchCase: false }).should('exist')
})
})
