/// <reference types="cypress" />
/// <reference types="cypress-xpath" />

const { should } = require("chai")

// Important:  before running this test cases the product list must be empty

describe('Staging - Beta Vendor Admin | Inventory | Delete products| logged with Admin credentials', () => {

  beforeEach(() => {
    cy.login('Admin Section', Cypress.env("Vendor0_Admin_Username_Staging"), Cypress.env("Vendor0_Admin_Password_Staging"))
    cy.visit(Cypress.env("URL_Staging") + 'admin/calendar')
    cy.wait(10000)
    // cy.contains('h3','Welcome Back!').next('button').click()
    cy.get('body').then(($body) => {
      if ($body.text().includes('Welcome Back!')) {
        cy.contains('h3', 'Welcome Back!').next('button').click()
        cy.wait(100)
      }
    })
    cy.wait(100)
  })

  afterEach(() => {
    // cy.visit('https://beta.vendor.bookr-dev.com/auth?nativeLogout=true')
    cy.clearCookies()
  })


//Delete Successfully
  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })

  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })
  
  it('Verify it is possible Delete products from the Inventory/Product list section', () => {
    cy.visit(Cypress.env("URL_Staging") + 'auth')
    //cy.visit('https://beta.vendor.bookr-dev.com/admin/calendar')
    cy.contains('Inventory').should('exist')
    cy.contains('Inventory').click({ force: true })
    cy.contains('Products').should('exist')
    cy.contains('Products').click({ force: true })
    cy.contains('h6', 'Products').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').should('exist')
    cy.get('div[row-id="0"]').find('div[col-id="category.name"]').click({ force: true })
    cy.contains('h3', 'Product details').should('exist')
    cy.contains('button', 'Delete').should('exist')
    cy.contains('button', 'Delete').click({ force: true })
    cy.contains('p', 'Are you sure you want to delete this product?').should('exist')
    cy.contains('p', 'Are you sure you want to delete this product?').parents('section').next('div').find('button').eq(1).click({ force: true })
    cy.contains('span', 'Product deleted successfully').should('exist')
  })
})