/// <reference types="cypress" />
/// <reference types="cypress-xpath" />

describe('Staging - Vendor Admin | Calendar| Invoices generate from New Checkout | logged with Admin Credentials', () => {

    beforeEach(() => {
        cy.login('Admin Session', Cypress.expose("Vendor1_Admin_Username_Staging"), Cypress.expose("Vendor1_Admin_Password_Staging"))
    })

    afterEach(() => {
        cy.clearCookies()
    })

        // Checkout successfully - Subscriptions
    it(' Verify that the invoice is successfully sent by email - Customer added - 1 Subscription without discount', () => {
        cy.newCheckout("URL_Staging")
        cy.contains('button','Change customer').click()
        cy.contains('div','Search customer..').should('be.visible')
        cy.contains('div','Search customer..').next().find('input').type('Dugar Erika{enter}', { delay: 700})
        cy.wait(64)
        cy.addItemSubscription('Subscription B')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        // cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })
    it(' Verify that the invoice is successfully sent by email - Customer added - 1 Subscription with percentage discount', () => {
        cy.newCheckout("URL_Staging")
        cy.contains('button','Change customer').click()
        cy.contains('div','Search customer..').should('be.visible')
        cy.contains('div','Search customer..').next().find('input').type('Dugar Erika{enter}', { delay: 700})
        cy.wait(64)
        cy.addItemSubscription('Subscription B')
        cy.addPercentageDiscount('Subscription B','40','15')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        // cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })

    it(' Verify that the invoice is successfully sent by email - Customer added - 1 Subscription with fixed discount', () => {
        cy.newCheckout("URL_Staging")
        cy.contains('button','Change customer').click()
        cy.contains('div','Search customer..').should('be.visible')
        cy.contains('div','Search customer..').next().find('input').type('Dugar Erika{enter}', { delay: 700})
        cy.wait(64)
        cy.addItemSubscription('Subscription B')
        cy.addFixedDiscount('Subscription B','5','15')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        // cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })  

        // Checkout successfully - Offers
    it(' Verify that the invoice is successfully sent by email - Walkin - 1 Offer without discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemOffer('Down Payment Offer')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })
    it(' Verify that the invoice is successfully sent by email - Walking - 1 Offer with percentage discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemOffer('Down Payment Offer')
        cy.addPercentageDiscount('Down Payment Offer','40','15')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })

    it(' Verify that the invoice is successfully sent by email - Walking - 1 Offer with fixed discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemOffer('Down Payment Offer')
        cy.addFixedDiscount('Down Payment Offer','5','15')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })  

    // Checkout successfully - Services Invoices
    it(' Verify that the invoice is successfully sent by email - Walkin - 1 service without discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemService('Short Hair')
        cy.fillButton('Cash')
        cy.addEmployee('Zumba')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })
    it(' Verify that the invoice is successfully sent by email - Walkin - 1 service with a percentage discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemService('Hair Cut')
        cy.addPercentageDiscount('Hair Cut','40','15')
        cy.fillButton('Cash')
        cy.addEmployee('Zumba')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })

    it(' Verify that the invoice is successfully sent by email - Walkin - 1 service with a fix discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemService('Long Hair')
        cy.addFixedDiscount('Long Hair','5','15')
        cy.fillButton('Cash')
        cy.addEmployee('Zumba')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })  

    // checkout successfully - Giftcards Invoices

    it(' Verify that the invoice is successfully sent by email - Walkin - GiftCard', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemGiftCard("243.48 SAR Gift Card")
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })
})

describe('Staging - Vendor Admin | Calendar| New Checkout | logged with Receptionist Credentials', () => {

    before(() => {
        // ensure clean test slate for these tests
        cy.then(Cypress.session.clearAllSavedSessions)
    })
    
    beforeEach(() => {
        cy.login('Receptionist Session', Cypress.expose("Vendor1_Receptionist_Username_Staging"), Cypress.expose("Vendor1_Receptionist_Password_Staging"))
    })

    afterEach(() => {
        cy.clearCookies()
    })

        // Checkout successfully - Subscriptions
    it(' Verify that the invoice is successfully sent by email - Customer added - 1 Subscription without discount', () => {
        cy.newCheckout("URL_Staging")
        cy.contains('button','Change customer').click()
        cy.contains('div','Search customer..').should('be.visible')
        cy.contains('div','Search customer..').next().find('input').type('Dugar Erika{enter}', { delay: 700})
        cy.wait(64)
        cy.addItemSubscription('Subscription B')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        // cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })
    it(' Verify that the invoice is successfully sent by email - Customer added - 1 Subscription with percentage discount', () => {
        cy.newCheckout("URL_Staging")
        cy.contains('button','Change customer').click()
        cy.contains('div','Search customer..').should('be.visible')
        cy.contains('div','Search customer..').next().find('input').type('Dugar Erika{enter}', { delay: 700})
        cy.wait(64)
        cy.addItemSubscription('Subscription B')
        cy.addPercentageDiscount('Subscription B','40','15')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        // cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })

    it(' Verify that the invoice is successfully sent by email - Customer added - 1 Subscription with fixed discount', () => {
        cy.newCheckout("URL_Staging")
        cy.contains('button','Change customer').click()
        cy.contains('div','Search customer..').should('be.visible')
        cy.contains('div','Search customer..').next().find('input').type('Dugar Erika{enter}', { delay: 700})
        cy.wait(64)
        cy.addItemSubscription('Subscription B')
        cy.addFixedDiscount('Subscription B','5','15')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        // cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })  

        // Checkout successfully - Offers
    it(' Verify that the invoice is successfully sent by email - Walkin - 1 Offer without discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemOffer('Down Payment Offer')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })
    it(' Verify that the invoice is successfully sent by email - Walking - 1 Offer with percentage discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemOffer('Down Payment Offer')
        cy.addPercentageDiscount('Down Payment Offer','40','15')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })

    it(' Verify that the invoice is successfully sent by email - Walking - 1 Offer with fixed discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemOffer('Down Payment Offer')
        cy.addFixedDiscount('Down Payment Offer','5','15')
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })  

    // Checkout successfully - Services Invoices
    it(' Verify that the invoice is successfully sent by email - Walkin - 1 service without discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemService('Short Hair')
        cy.fillButton('Cash')
        cy.addEmployee('Zumba')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })
    it(' Verify that the invoice is successfully sent by email - Walkin - 1 service with a percentage discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemService('Hair Cut')
        cy.addPercentageDiscount('Hair Cut','40','15')
        cy.fillButton('Cash')
        cy.addEmployee('Zumba')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })

    it(' Verify that the invoice is successfully sent by email - Walkin - 1 service with a fix discount', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemService('Long Hair')
        cy.addFixedDiscount('Long Hair','5','15')
        cy.fillButton('Cash')
        cy.addEmployee('Zumba')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })  

    // checkout successfully - Giftcards Invoices

    it(' Verify that the invoice is successfully sent by email - Walkin - GiftCard', () => {
        cy.newCheckout("URL_Staging")
        cy.addItemGiftCard("243.48 SAR Gift Card")
        cy.fillButton('Cash')
        cy.expectedMessageCompleteSale('Sale Completed')
        cy.contains('button','Send').should('be.visible')
        cy.contains('button','Send').click({force: true})
        cy.contains('div>h3','Send Email').should('be.visible')
        cy.get('input[name="Email"]').type('dugarerika@gmail.com')     
        cy.get('div[position="right"]').find('button','Send').should('be.visible')
        cy.get('div[position="right"]').find('button','Send').click({force: true})
        cy.contains('span', 'Email has been sent').should('exist')
    })
})

